apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/rodenj1/homelab
    path: clusters/home-lab/
    targetRevision: main
    directory:
      recurse: true
      include: '{**/app.yaml,**/values.yaml}'
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
