apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-bigspray
  namespace: traefik
spec:
  secretName: argocd-bigspray-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "argocd.k3s.big-spray.com"
  dnsNames:
  - "argocd.k3s.big-spray.com"