apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.k3s.big-spray.com`)
      priority: 10
      # middlewares: 
      #   - name: argocd-headers 
      #     namespace: argocd
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`argocd.k3s.big-spray.com`) && Header(`Content-Type`, `application/grpc`)
      priority: 11
      # middlewares: 
      #   - name: argocd-headers 
      #     namespace: argocd
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
  tls:
    # certResolver: default
    secretName: argocd-bigspray-tls