apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alertmanager-bigspray
  namespace: monitoring
spec:
  secretName: alertmanager-bigspray-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "alertmanager.k3s.big-spray.com"
  dnsNames:
  - "alertmanager.k3s.big-spray.com"