apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-bigspray
  namespace: monitoring
spec:
  secretName: grafana-bigspray-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "grafana.k3s.big-spray.com"
  dnsNames:
  - "grafana.k3s.big-spray.com"