apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
spec:
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/rodenj1/homelab
    targetRevision: main
    path: clusters/home-lab/infra/metallb/manifests
  #   path: ''
  #   repoURL: https://metallb.github.io/metallb
  #   targetRevision: 0.14.9
  #   chart: metallb
  # sources: 
  #   - repoURL: https://metallb.github.io/metallb
  #     chart: metallb
  #     targetRevision: 0.14.9
  #   - repoURL: https://github.com/rodenj1/homelab
  #     targetRevision: main
  #     path: clusters/home-lab/infra/metallb
  project: default
syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true