apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  sources:
    
    # - repoURL: https://prometheus-community.github.io/helm-charts
    #   targetRevision: 20.0.0
    #   chart: prometheus-operator-crds
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 72.5.3
      chart: kube-prometheus-stack
      helm:
        # parameters:
        #   - name: crds.enabled
        #     value: 'true'
        #   - name: crds.upgradeJob.enabled
        #     value: 'false'
        #   - name: fullnameOverride
        #     value: 'prometheus'
        #   - name: alertmanager.fullnameOverride
        #     value: 'alertmanager'
        #   - name: grafana.fullnameOverride
        #     value: 'grafana'
        #   - name: kubeControllerManager.endpoints[0]
        #     value: '10.10.0.5'
        #   - name: kubeControllerManager.endpoints[1]
        #     value: '10.10.0.6'
        #   - name: kubeControllerManager.endpoints[2]
        #     value: '10.10.0.6'
        #   - name: kubeEtcd.endpoints[0]
        #     value: '10.10.0.5'
        #   - name: kubeEtcd.endpoints[1]
        #     value: '10.10.0.6'
        #   - name: kubeEtcd.endpoints[2]
        #     value: '10.10.0.6'
        #   - name: kubeScheduler.endpoints[0]
        #     value: '10.10.0.5'
        #   - name: kubeScheduler.endpoints[1]
        #     value: '10.10.0.6'
        #   - name: kubeScheduler.endpoints[2]
        #     value: '10.10.0.6'
        #   - name: kubeProxy.endpoints[0]
        #     value: '10.10.0.5'
        #   - name: kubeProxy.endpoints[1]
        #     value: '10.10.0.6'
        #   - name: kubeProxy.endpoints[2]
        #     value: '10.10.0.6'
        valueFiles:
          - $values/clusters/home-lab/infra/prometheus/values.yaml
    - repoURL: https://github.com/rodenj1/homelab
      # path: 'clusters/home-lab/infra/prometheus'
      targetRevision: main
      ref: values
  # source:
    
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true