apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  sources:
    
    # - repoURL: https://prometheus-community.github.io/helm-charts
    #   targetRevision: 20.0.0
    #   chart: prometheus-operator-crds
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 72.3.1
      chart: kube-prometheus-stack
      helm:
        valueFiles:
          - $values/clusters/home-lab/argo-root-apps/prometheus-values.yaml
    - repoURL: https://github.com/rodenj1/homelab
      targetRevision: main
      ref: values
  # source:
    
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true