apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc

  sources: 
    - repoURL: https://traefik.github.io/charts
      targetRevision: 35.3.0
      chart: traefik
      helm:
        parameters:
          - name: deployment.replicas
            value: '3'
          - name: ingressRoute.healthcheck.enabled
            value: 'true'
          - name: providers.kubernetesCRD.enabled
            value: 'true'
          - name: providers.kubernetesCRD.ingressClass
            value: traefik-external
          - name: providers.kubernetesCRD.allowExternalNameServices
            value: 'true'
          - name: ports.web.redirections.entryPoint.to
            value: websecure
          - name: ports.web.redirections.entryPoint.scheme
            value: https
          - name: ports.web.redirections.entryPoint.permanent
            value: 'true'
          - name: ports.web.redirections.entryPoint.priority
            value: '10'
          - name: providers.kubernetesIngress.enabled
            value: 'true'
          - name: providers.kubernetesIngress.allowExternalNameServices
            value: 'true'
          - name: providers.kubernetesIngress.publishedService.enabled
            value: 'false'
          - name: rbac.enabled
            value: 'true'
          - name: service.enabled
            value: 'true'
          - name: service.spec.loadBalancerIP
            value: 192.168.100.60
          # - name: metrics.prometheus.enabled 
          #   value: 'true' 
          # - name: metrics.prometheus.addEntryPointsLabels 
          #   value: 'true' 
          # - name: metrics.prometheus.addServicesLabels 
          #   value: 'true'
          - name: ports.metrics.port 
            value: '9100' 
          - name: ports.metrics.expose 
            value: 'true'


        # valueFiles:
        #   - traefik-values.yaml
    - repoURL: https://github.com/rodenj1/homelab
      targetRevision: main
      path: clusters/home-lab/infra/traefik/manifests

    - repoURL: https://github.com/rodenj1/homelab
      targetRevision: main
      path: clusters/home-lab/infra/traefik/dashboard
  project: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true