apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.17.2
      helm:
        parameters:
          - name: crds.enabled
            value: 'true'
          # - name: podDnsPolicy
          #   value: 'None'
          # - name: extraArgs[0]
          #   value: '--dns01-recursive-nameservers=1.1.1.1:53,9.9.9.9:53'
          # - name: extraArgs[1]
          #   value: '--dns01-recursive-nameservers-only'
          # - name: podDnsConfig.nameservers[0]
          #   value: '1.1.1.1'
          # - name: podDnsConfig.nameservers[1]
          #   value: '9.9.9.9'
    # - repoURL: https://github.com/rodenj1/homelab
    #   targetRevision: main
    #   path: clusters/home-lab/infra/cert-manager/manifests

        
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
