apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 7.9.0
    helm:
      parameters:
        - name: server.insecure
          value: 'true'
        - name: configs.cm.resource.customizations
          value: |
            apiextensions.k8s.io/CustomResourceDefinition:
              ignoreDifferences:
                jsonPointers:
                - /spec/conversion/webhook/clientConfig/caBundle
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
