apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 8.0.0
      helm:
        parameters:
          - name: server.insecure
            value: 'true'
          - name: configs.params."server.insecure"
            value: 'true'
    - repoURL: https://github.com/rodenj1/homelab 
      targetRevision: main 
      path: clusters/home-lab/infra/argocd/manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
