server:
  extraArgs:
    - --insecure

configs:
  cm:
    resource.customizations: |
      apiextensions.k8s.io/CustomResourceDefinition:
        ignoreDifferences: |
          jsonPointers:
          - /spec/conversion/webhook/clientConfig/caBundle
