apiVersion: v1
kind: Pod
metadata:
  name: kube-vip
  namespace: kube-system
  annotations:
    kube-vip.io/manifest-version: "v0.9.1"
spec:
  hostNetwork: true
  containers:
  - name: kube-vip
    image: ghcr.io/kube-vip/kube-vip:v0.9.1
    args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: vip_interface
      value: "eth0"
    - name: address
      value: "192.168.100.59"
    - name: cp_enable
      value: "true"
    - name: svc_enable
      value: "false"
    - name: vip_leaderelection
      value: "true"
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
