# values.yaml for kube-vip via Helm in control-plane VIP mode

image:
  repository: ghcr.io/kube-vip/kube-vip
  pullPolicy: IfNotPresent

config:
  # This should match your kube-vip virtual IP (e.g. first in MetalLB or manually chosen)
  address: "192.168.100.59"

env:
  vip_interface: "eth0"         # Your backend cluster interface
  vip_arp: "true"
  vip_cidr: "32"
  lb_enable: "false"            # Disable kube-vip load balancer mode
  cp_enable: "true"             # Enable control-plane VIP mode
  svc_enable: "false"           # Disable service VIP mode (use MetalLB)
  svc_election: "false"
  vip_leaderelection: "true"    # Enable leader election for HA

extraArgs: {}

envValueFrom: {}

envFrom: []

extraLabels: {}

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""
namespaceOverride: "kube-system"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  capabilities:
    add:
      - NET_ADMIN
      - NET_RAW
    drop:
      - ALL

resources: {}

volumes: []
volumeMounts: []

hostAliases: []

nodeSelector: {}

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

affinity: {}

podMonitor:
  enabled: false
  labels: {}
  annotations: {}

priorityClassName: ""
