apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  ignoreDifferences:
    - group: '*'
      kind: '*'
      jsonPointers:
        - /preserveUnknownFields
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.8.1
      helm:
        parameters:
          - name: preUpgradeChecker.jobEnabled
            value: 'false'
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system