apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.8.1
      helm:
        parameters:
          - name: preUpgradeChecker.jobEnabled
            value: 'false'
          - name: preUpgradeChecker.upgradeVersionCheck
            value: 'false'
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system